# Generated by Django 4.1.3 on 2022-11-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_user_is_active_alter_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('image', models.URLField(unique=True)),
                ('quote', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('fact1', models.CharField(max_length=200)),
                ('fact2', models.CharField(max_length=200)),
                ('fact3', models.CharField(max_length=200)),
                ('short', models.URLField()),
            ],
        ),
    ]
